# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iris.proto',
  package='ml',
  syntax='proto3',
  serialized_pb=_b('\n\niris.proto\x12\x02ml\"j\n\x12IrisPredictRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x01\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x01\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x01\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x01\"#\n\x10IrisPredictReply\x12\x0f\n\x07species\x18\x01 \x01(\x05\x32U\n\rIrisPredictor\x12\x44\n\x12PredictIrisSpecies\x12\x16.ml.IrisPredictRequest\x1a\x14.ml.IrisPredictReply\"\x00\x42(\n\x13io.grpc.examples.mlB\tIrisProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_IRISPREDICTREQUEST = _descriptor.Descriptor(
  name='IrisPredictRequest',
  full_name='ml.IrisPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='ml.IrisPredictRequest.sepal_length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='ml.IrisPredictRequest.sepal_width', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='ml.IrisPredictRequest.petal_length', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='ml.IrisPredictRequest.petal_width', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=124,
)


_IRISPREDICTREPLY = _descriptor.Descriptor(
  name='IrisPredictReply',
  full_name='ml.IrisPredictReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='species', full_name='ml.IrisPredictReply.species', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['IrisPredictRequest'] = _IRISPREDICTREQUEST
DESCRIPTOR.message_types_by_name['IrisPredictReply'] = _IRISPREDICTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IrisPredictRequest = _reflection.GeneratedProtocolMessageType('IrisPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _IRISPREDICTREQUEST,
  __module__ = 'iris_pb2'
  # @@protoc_insertion_point(class_scope:ml.IrisPredictRequest)
  ))
_sym_db.RegisterMessage(IrisPredictRequest)

IrisPredictReply = _reflection.GeneratedProtocolMessageType('IrisPredictReply', (_message.Message,), dict(
  DESCRIPTOR = _IRISPREDICTREPLY,
  __module__ = 'iris_pb2'
  # @@protoc_insertion_point(class_scope:ml.IrisPredictReply)
  ))
_sym_db.RegisterMessage(IrisPredictReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023io.grpc.examples.mlB\tIrisProtoP\001\242\002\003HLW'))

_IRISPREDICTOR = _descriptor.ServiceDescriptor(
  name='IrisPredictor',
  full_name='ml.IrisPredictor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=163,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictIrisSpecies',
    full_name='ml.IrisPredictor.PredictIrisSpecies',
    index=0,
    containing_service=None,
    input_type=_IRISPREDICTREQUEST,
    output_type=_IRISPREDICTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IRISPREDICTOR)

DESCRIPTOR.services_by_name['IrisPredictor'] = _IRISPREDICTOR

# @@protoc_insertion_point(module_scope)
